// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhltdIRw51vTycvfeCYALxAxxO9bcum1o',
    appId: '1:359795794071:web:55d533d2fd6cd42b2d49d2',
    messagingSenderId: '359795794071',
    projectId: 'cdss-quiz',
    authDomain: 'cdss-quiz.firebaseapp.com',
    storageBucket: 'cdss-quiz.appspot.com',
    measurementId: 'G-JRCKHC40Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmEgUnITSmoDYcE1442a0BwnkMFBYrcHQ',
    appId: '1:359795794071:android:34695bf449dfb81c2d49d2',
    messagingSenderId: '359795794071',
    projectId: 'cdss-quiz',
    storageBucket: 'cdss-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhe0TiuCLe_DoqmctU_-riZrdGWinYWpk',
    appId: '1:359795794071:ios:5dabe194698f93302d49d2',
    messagingSenderId: '359795794071',
    projectId: 'cdss-quiz',
    storageBucket: 'cdss-quiz.appspot.com',
    iosClientId: '359795794071-rveqlo6e7kjeoa8vkea1aldu0qlc8fkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cdssQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhe0TiuCLe_DoqmctU_-riZrdGWinYWpk',
    appId: '1:359795794071:ios:5dabe194698f93302d49d2',
    messagingSenderId: '359795794071',
    projectId: 'cdss-quiz',
    storageBucket: 'cdss-quiz.appspot.com',
    iosClientId: '359795794071-rveqlo6e7kjeoa8vkea1aldu0qlc8fkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cdssQuiz',
  );
}
